### ISSUE TITLE
generate_gold_standard returns an error

### ISSUE THREAD

**Issue by Marius1311** [dynverse/dyngen#16]
I'm basically just running the example outlined in your readme on the github. When I call `model <- generate_gold_standard(model)`, I get

```R
Generating gold standard mod changes
Precompiling reactions for gold standard
Running gold simulations
  |==================================================| 100% elapsed=00s, remaining~00s
Error in x$.self$finalize() : attempt to apply non-function
In addition: Warning message:
unnest() has a new interface. See ?unnest for details.
Try `df %>% unnest(c(mod_diff, substate))`, with `mutate()` if needed
```

The function however still seems to finish. When I call the respective plotting function, `plot_gold_simulations(model)`, the plot I get however looks a lot more rough than the screenshot in the readme. Any ideas?

**Comment by rcannood** [comment]
Hello Marius! 

I apologise, I seem to have missed your post.

The error message started occurring at some point due to updates in underlying packages and is related to how the Rcpp code is cleaned up -- I think. It has no effect on the eventual output, but I should get around to debugging this error message at some point.

As for the plot that you get ending up different from what you saw in the README (this has in the meantime been moved to a [vignette](https://github.com/dynverse/dyngen/blob/master/vignettes/getting_started.md)... with ... no figures.. I'll have a look at that!), could be due me not having updated the tutorial code after making changes to the package. 

If you update dyngen and run the code in the tutorial again, I hope you get the desired results. If not, feel free to let me know! :+1:  Does this answer your question?

Kind regards, 
Robrecht

**Comment by Marius1311** [comment]
Thanks Robrecht! I will check this out and get back to you in case the problem persists.

**Comment by rcannood** [comment]
This issue appears to have been solved, closing this issue.
