### ISSUE TITLE
Using `experiment_synchronised`

### ISSUE THREAD

**Issue by ntanmayee** [dynverse/dyngen#34]
Hello, thanks for this great simulation engine! I'm excited to try it in some of my own work. 

I have some questions about using `experiment_synchronised`
1. What does the `pct_between` parameter mean? I'm not sure I understand what "unused time" means.

2. After using the `generate_experiment` function to generate the experiment data, which parameter has the mapping from cell to timepoint? As far as I can see, there are three variables related to time - `sim_time`, `simulation_i` and `time`. (It looks like `simulation_i` stores the timepoint, just from checking unique values, but I would like to be sure that my suspicion is correct.)

**Comment by rcannood** [comment]
Hi Tanmayee,

Thanks for your interesting questions! I'll make some changes to the package based on the answers provided below. Do my answers below answer your questions sufficiently?

Kind regards,
Robrecht

### 1. What does the pct_between parameter mean? I'm not sure I understand what "unused time" means.

I see that the documentation for this function doesn't sufficiently explain what the parameters do. It is mentioned briefly in the [Methods section](https://www.nature.com/articles/s41467-021-24152-2#Sec4) of the paper in the section named "Sample cells":

> **Sample cells**
> 
> In this step, N cells are sampled from the simulations. Two approaches are implemented: sampling from an unsynchronised population of single cells (snapshot) or sampling at multiple time points in a synchronised population (time series).
> 
> **Snapshot**. The backbone consists of several states linked together by transition edges with length Li, to which the different states in the different simulations have been mapped (Supplementary Fig. 7A). From each transition, 𝑁𝑖=𝑁/𝐿𝑖∑𝐿𝑖 cells are sampled uniformly, rounded such that ∑Ni = N.
> 
> **Time series**. Assuming that the final time of the simulation is T, the interval [0, T] is divided into k equal intervals of width w separated by k − 1 gaps of width g. Ni = N/k cells are sampled uniformly from each interval (Supplementary Fig. 7B), rounded such that ∑Ni = N. By default, k = 8 and g = 0.75. For usual dyngen simulations, 10 ≤ T ≤ 20. For larger values of T, k and g should be increased accordingly.

![Screenshot from 2021-07-09 08-58-05](https://user-images.githubusercontent.com/553642/125036884-cf707480-e093-11eb-9ed7-64ed66ff27b7.png)


↑ In this last paragraph, T corresponds to `model$simulation_params$total_time`, k is the `num_timepoints` parameter of `experiment_synchronised()` and g is the `pct_between` parameter of the same function. The 'unused time' are the sections of your simulation (as determined by the pct_between parameter) from which no cells will get sampled.

### 2. After using the generate_experiment function to generate the experiment data, which parameter has the mapping from cell to timepoint?

`simulation_i` is definitely not the time point! Take a look at this example:

```r
library(tidyverse)
library(dyngen)

set.seed(1)
out <-
  initialise_model(
    backbone = backbone_bifurcating(),
    simulation_params = simulation_default(
      experiment_params = simulation_type_wild_type(num_simulations = 100)
    ),
    experiment = experiment_synchronised(num_timepoints = 8, pct_between = 0.75)
  ) %>% 
  generate_dataset()

plot_simulations(out$model)
```

![plot_zoom](https://user-images.githubusercontent.com/553642/125038524-cb455680-e095-11eb-94f1-0e3f0c23d627.png)

↑ This simulates a bifurcating dataset with 100 simulations from which cells will be sampled.

This is what `cell_info` looks like:
```r
cell_info <- out$dataset$cell_info
cell_info
ggplot(cell_info) + 
  geom_point(aes(sim_time, simulation_i)) +
  theme_bw()
```
```
> cell_info
# A tibble: 1,000 x 4
   cell_id step_ix simulation_i sim_time
   <chr>     <int>        <int>    <dbl>
 1 cell1     15945           70    388. 
 2 cell2     12301           54    468. 
 3 cell3     18394           81    108. 
 4 cell4      5362           24    192. 
 5 cell5      6758           30    280. 
 6 cell6     11364           50    384. 
 7 cell7     19058           84     16.0
 8 cell8     22787          100    276. 
 9 cell9     10287           45    656. 
10 cell10    19102           84    192. 
# … with 990 more rows
```
![plot_zoom2](https://user-images.githubusercontent.com/553642/125038739-0e072e80-e096-11eb-8cc0-d188e5781549.png)

So simulation_i is the dyngen simulation index from which the cell was drawn, not the time point. `sim_time` is time in this simulation at which the cell was sampled. 

And this is where I need to apologise! You can clearly see that there are 8 groups of cells and that there are large gaps between the groups of cells, but I forgot to save the information of which time point group they belong to in cell info!

A temporary workaround can be to use clustering to retrieve the timepoint groups. Make sure to verify that the clustering is done correctly!

```r
cell_info$timepoint_group <- 
  kmeans(
    x = cbind(cell_info$sim_time, cell_info$sim_time, cell_info$sim_time, cell_info$sim_time), 
    centers = out$model$experiment_params$num_timepoints
  )$cluster
ggplot(cell_info) + 
  geom_point(aes(sim_time, simulation_i, colour = factor(timepoint_group))) +
  theme_bw()
```
![plot_zoom3](https://user-images.githubusercontent.com/553642/125039907-507d3b00-e097-11eb-836c-3dcded521d5a.png)


In an next release of dyngen, I'll change the code so that the timepoint groups are simply returned in the cell info.

**Comment by rcannood** [comment]
Update: in the `dynverse/dyngen@devel` branch, the timepoint group is now being returned again:

```
> # devtools::install_github("dynverse/dyngen@devel")
> cell_info
# A tibble: 1,000 x 5
   cell_id step_ix simulation_i sim_time timepoint_group
   <chr>     <int>        <int>    <dbl>           <dbl>
 1 cell1      7789           37   620.                 7
 2 cell2     14596           70     0                  0
 3 cell3      5382           26   276.                 3
 4 cell4     19329           92   360.                 4
 5 cell5      9410           45   352.                 4
 6 cell6     18607           89     4.01               0
 7 cell7      5172           25   280.                 3
 8 cell8     15952           76   356.                 4
 9 cell9      3780           18   620.                 7
10 cell10    12275           59     0                  0
```

This fix will be included in the next dyngen release.

**Comment by ntanmayee** [comment]
Thank you very much for your detailed and clear response!
